[package]
name = "warp-pkl-moment"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
sea-orm = { version = "0.12.15", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
shuttle-runtime = "0.44.0"
shuttle-warp = "0.44.0"
tokio = "1.26.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
warp = "0.3.7"
